version: '2.1'
services:
  config:
    image: iremember/config:latest
    container_name: config
    ports:
       - "8071:8071"
    environment:
      ENCRYPT_KEY: ${ENCRYPT_KEY} #"IMSYMMETRIC"
    networks:
      backend:
        aliases:
          - "config"

  eureka:
    image: iremember/eureka:latest
    container_name: eureka
    ports:
       - "8070:8070"
    volumes:
    - ./wait-for-it.sh:/wait-for-it.sh
    depends_on:
      config:
        condition: service_started
    command: ["/wait-for-it.sh", "config:8071", "--","java", "org.springframework.boot.loader.JarLauncher"]
    networks:
      backend:
        aliases:
          - "eureka"
  gateway:
    image: iremember/gateway:latest
    container_name: gateway
    ports:
      - "8072:8072"
    volumes:
    - ./wait-for-it.sh:/wait-for-it.sh
    environment:
#      PROFILE: "default"
      SERVER_PORT: "8072"
      CONFIGSERVER_URI: "http://config:8071"
      EUREKASERVER_URI: "http://eureka:8070/eureka/"
      EUREKASERVER_PORT: "8070"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      config:
        condition: service_started
      eureka:
        condition: service_started
    command: ["/wait-for-it.sh", "eureka:8070", "--","java", "org.springframework.boot.loader.JarLauncher"]
    networks:
      backend:
        aliases:
          - "gateway"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - 9411: 9411
    networks:
      backend:
        aliases:
        - "zipkin"
networks:
  backend:
    driver: bridge

#mvn clean package dockerfile:build && docker-compose -f docker/docker-compose.yml up